version: '3.9'
services:
  receipt-service:
    container_name: receipt-service
    image: bumblebear/receipttask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:15.1-alpine
    container_name: postgresdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=post
      - POSTGRES_PASSWORD=tsop
      - POSTGRES_DB=receiptDB
      - POSTGRES_HOST_AUTH_METHOD=trust
